services:
  grpc-service:
      build: .
      ports:
        - "${GRPC_PORT:-8080}:${GRPC_PORT:-8080}"
      environment:
        GRPC_PORT: ${GRPC_PORT:-8080}
        TARANTOOL_HOST: tarantool
        TARANTOOL_PORT: ${TARANTOOL_PORT:-3301}
        TARANTOOL_USERNAME: ${TARANTOOL_USERNAME}
        TARANTOOL_PASSWORD: ${TARANTOOL_PASSWORD}
      depends_on:
        - tarantool
      restart: on-failure

  tarantool:
    image: tarantool/tarantool:3.2.3
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua
      - data:/var/lib/tarantool
    command: ["tarantool", "/opt/tarantool/init.lua"]
    environment:
      TARANTOOL_USER_NAME: ${TARANTOOL_USERNAME}
      TARANTOOL_USER_PASSWORD: ${TARANTOOL_PASSWORD}
      TARANTOOL_PORT: ${TARANTOOL_PORT}
      TARANTOOL_MEMORY: ${TARANTOOL_MEMORY}
      TARANTOOL_LOG_LEVEL: ${TARANTOOL_LOG_LEVEL}
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 3301 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  data: