services:
  tarantool:
    image: tarantool/tarantool:3.2.3
    ports:
      - "3001:3001"
    volumes:
      - ./tarantool/init.lua:/opt/tarantool/init.lua
      - data:/var/lib/tarantool
    command:
      - tarantool /opt/tarantool/init.lua
    environment:
      TARANTOOL_USER_NAME: ${USERNAME}
      TARANTOOL_USER_PASSWORD: ${PASSWORD}
      TARANTOOL_PORT: ${PORT}
    healthcheck:
      test: [ "CMD", "tarantool", "-e", "require('net.box').connect('localhost:3301'):ping()" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  data: